// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1LgRe04q9NQwuoS-O1re562SGbr0CCws',
    appId: '1:328132744933:web:efcf4322db36f068fbe60c',
    messagingSenderId: '328132744933',
    projectId: 'note-app-7752',
    authDomain: 'note-app-7752.firebaseapp.com',
    storageBucket: 'note-app-7752.firebasestorage.app',
    measurementId: 'G-9PLVBMESFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgwzhm9a8z-CUZbcHEjaJ7CenULg-oc4I',
    appId: '1:328132744933:android:c23b2562dfa69e9efbe60c',
    messagingSenderId: '328132744933',
    projectId: 'note-app-7752',
    storageBucket: 'note-app-7752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_qdnuhLLcNpbDX61sEGXHSJ1Tdop7cmQ',
    appId: '1:328132744933:ios:7b507f0d015df922fbe60c',
    messagingSenderId: '328132744933',
    projectId: 'note-app-7752',
    storageBucket: 'note-app-7752.firebasestorage.app',
    iosBundleId: 'com.noteapp.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_qdnuhLLcNpbDX61sEGXHSJ1Tdop7cmQ',
    appId: '1:328132744933:ios:7b507f0d015df922fbe60c',
    messagingSenderId: '328132744933',
    projectId: 'note-app-7752',
    storageBucket: 'note-app-7752.firebasestorage.app',
    iosBundleId: 'com.noteapp.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1LgRe04q9NQwuoS-O1re562SGbr0CCws',
    appId: '1:328132744933:web:ec3965157171b5cbfbe60c',
    messagingSenderId: '328132744933',
    projectId: 'note-app-7752',
    authDomain: 'note-app-7752.firebaseapp.com',
    storageBucket: 'note-app-7752.firebasestorage.app',
    measurementId: 'G-KCX3CVBJWV',
  );

}